/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'orderId' : IDL.Nat,
  'invoiceNumber' : IDL.Text,
  'issuedAt' : IDL.Int,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customerPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalInCents' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const PaymentTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'method' : IDL.Text,
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const SeedProduct = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const PaymentOption = IDL.Record({
  'method' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const SalesStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalItemsSold' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPaymentTransactions' : IDL.Func(
      [],
      [IDL.Vec(PaymentTransaction)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(SeedProduct)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPaymentOptions' : IDL.Func([], [IDL.Vec(PaymentOption)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SeedProduct)],
      ['query'],
    ),
  'getSalesStats' : IDL.Func([], [SalesStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(SeedProduct)], ['query']),
  'togglePaymentOption' : IDL.Func([IDL.Text], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'orderId' : IDL.Nat,
    'invoiceNumber' : IDL.Text,
    'issuedAt' : IDL.Int,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customerPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalInCents' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'method' : IDL.Text,
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const SeedProduct = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const PaymentOption = IDL.Record({
    'method' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const SalesStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalItemsSold' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPaymentTransactions' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(SeedProduct)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPaymentOptions' : IDL.Func([], [IDL.Vec(PaymentOption)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SeedProduct)],
        ['query'],
      ),
    'getSalesStats' : IDL.Func([], [SalesStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(SeedProduct)], ['query']),
    'togglePaymentOption' : IDL.Func([IDL.Text], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };