/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Invoice {
  'id' : bigint,
  'orderId' : bigint,
  'invoiceNumber' : string,
  'issuedAt' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'paymentStatus' : string,
  'paymentMethod' : string,
  'customerPrincipal' : Principal,
  'createdAt' : bigint,
  'totalInCents' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export interface PaymentOption { 'method' : string, 'enabled' : boolean }
export interface PaymentTransaction {
  'id' : bigint,
  'status' : string,
  'method' : string,
  'orderId' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface SalesStats {
  'totalOrders' : bigint,
  'totalItemsSold' : bigint,
  'totalRevenue' : bigint,
}
export interface SeedProduct {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'priceInCents' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'getAllProducts' : ActorMethod<[], Array<SeedProduct>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPaymentOptions' : ActorMethod<[], Array<PaymentOption>>,
  'getProductsByCategory' : ActorMethod<[string], Array<SeedProduct>>,
  'getSalesStats' : ActorMethod<[], SalesStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<SeedProduct>>,
  'togglePaymentOption' : ActorMethod<[string], undefined>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];